### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [dajare/anthony-trollope_the-dukes-children#1]
# Semantics

- [x] The following foreign-language phrases were wrapped in `span`s when they should be `i`s:

- chapter-4: “De l’audace, et encore de l’audace, et toujours de l’audace.”
- chapter-9: “in medias res” (this is in MW, but this falls in under [8.2.9.9](https://standardebooks.org/manual/1.7.0/8-typography#8.2.9.9))
- chapter-22: “Solve senescentem”
- chapter-25: “dura ilia”
- chapter-25: “Scandunt eodum quo dominus minae”
- chapter-28: “blasées habituées”
- chapter-51: “locus poenitentiae” (it’s in the MW legal dictionary, not the main dictionary)
- chapter-65: “Facilis descensus Averni” (this does seem to be in MW, but it calls it a Latin quotation so I don’t really buy that this should be unitalicized)
- chapter-65: “Noctes atque dies patet atri janua Ditis”

- [x] chapter-62: You removed the quotation marks around “Bayley’s” but didn’t italicize it or give it a semantic.

## Letters

- [x] chapter-13: “My dear Mrs. Finn” should be a `z3998:salutation`.
- [x] chapter-14: Ditto for “My dear Father.”
- [x] chapter-15: For the May 18 letter, both the dateline and salutation should be in the header. See [7.7.2.1](https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.7.2.1).
- [x] chapter-22: Ditto for the 3rd June letter.
- [x] chapter-44: Ditto for the Sept. 14 letter.
- [x] chapter-56: The 15th December letter has the header problem like the three bullets before, but also you used `z3998:valediction` where you meant `z3998:salutation`.
- [x] chapter-56: “My dear Mabel” was mistyped as a valediction instead of a salutation.
- [x] chapter-58: The header problem appears again in the 18th December letter.

# Typography

- [x] I think your titlecase exception is incorrect. SEMOS doesn’t exactly cover this case, but the in 8.67 of the Chicago Manual of Style (our backup) it says, regarding names of institutions and companies, “A *the* preceeding the name, even when part of the official title, is lowercased in running text.” I guess technically the title is not running text, but I think both the style rules of our titlecase logic and the CMOS point to leaving “the” uncapitalized.

# Meta

- [x] `5c92dbabebb07d6eaf5ca05d35643c6a4d107771`: In this commit, you mark changing quotes to italics for a title as editorial, but you do the same thing in `fd690d4c3b8884e7d201e83cd11a5fd40a327e4c` without marking that one as editorial. I am of the opinion that this is in fact, not editorial, so let’s mark both as non-editorial to be consistent.

**Comment by dajare** [comment]
Thanks once again, Weijia! All done, with just a few comments (see "Typography" especially):

- c62, "Bayley's" - I reconsidered; the notes to the Oxford World Classics edition italicize this, so I've overturned my previous decision (based on some research!). And there are no other instances in the SE corpus....
- **Letters** - oh my, that's embarrassing! I see I misread my "sample letter" I'd copied out of the manual (line divisions fell unfortunately) into a separate file for quick reference. Oops, and apologies.
- **Typography** - I've lowercased the "T" for the running text instances, but retained it in the ToC. I've based this on David Griggs's precedent in *[The Last Chronicle of Barset](https://github.com/search?q=org%3Astandardebooks+%2F%28%3F-i%29%5Ba-z%5D+The+%2F+path%3Atoc.xhtml&type=code)*, but this can be tweaked if need be, of course. 
- **Meta** - must remember that thing about quotes-to-italics: Vince told me the same thing. Guess I'm nervous about those, but will try to be bold. :)

Will leave note on Google Groups now.

**Comment by weijia-cheng** [comment]
Ok, linting again turns up a few issues, having to do with the changes we made to italics. `t-007` is a false positive but the others should be fixed.

**Comment by dajare** [comment]
@weijia-cheng Thanks! I should have picked those up... Sorry. (Will get these things in my head eventually!) Now fixed. Ready for Alex?? :/

**Comment by weijia-cheng** [comment]
Sorry, one last thing. Since we know the lint issue is a false alarm we should categorize that in the exceptions file.

**Comment by dajare** [comment]
And that even flitted through my brain. Should have acted! Sorry again, and now doen. Hope this is the last "gotcha"! 😬 @weijia-cheng
